using System.Globalization;
using System.Text;
using MillBurn.Core;

namespace MillBurn.Export;

/// <summary>
/// Writes an <see cref="Artwork"/> as SVG.
///
/// This is the whole laser output path (Documentation/04, section 1), so it is held to the same
/// standard as the G-code emitter rather than treated as a preview format:
///
/// - **Real millimetres.** <c>width="100mm" viewBox="0 0 100 80"</c>, never DPI pixels. A scale
///   error here is a scrapped board.
/// - **Deterministic bytes.** Invariant formatting, fixed precision, stable ordering, no
///   timestamp unless one is supplied. Two runs of the same input are byte-identical, which is
///   what makes the output testable by hash instead of by eye.
/// - **Arcs stay arcs.** An SVG <c>A</c> command carries a Gerber arc through unchanged.
/// - **Explicit per-element colour** for the LightBurn profile, because layer assignment there is
///   by stroke colour and a stylesheet may not survive the import.
///
/// Compare pcb2gcode's <c>svg_writer.cpp</c>, which gives every polygon a random RGB colour. That
/// is the worst available choice for a laser target: colour is exactly the channel the importer
/// reads to decide which cut layer a shape belongs to.
/// </summary>
public static class SvgWriter
{
    /// <summary>Decimals kept on every coordinate. Four is 0.1 um — far below any machine's step.</summary>
    private const int Decimals = 4;

    private const string NumberFormat = "0.####";

    public static void WriteFile(string path, Artwork artwork, SvgPage page, SvgExportOptions options)
    {
        ArgumentNullException.ThrowIfNull(path);

        // Explicit UTF-8 without a BOM: some importers choke on one, and the golden tests compare
        // bytes.
        File.WriteAllText(path, Write(artwork, page, options), new UTF8Encoding(false));
    }

    public static string Write(Artwork artwork, SvgPage page, SvgExportOptions options)
    {
        ArgumentNullException.ThrowIfNull(artwork);
        ArgumentNullException.ThrowIfNull(page);
        ArgumentNullException.ThrowIfNull(options);

        var sb = new StringBuilder(4096);
        var profile = options.Profile;

        sb.Append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
        sb.Append("<svg xmlns=\"http://www.w3.org/2000/svg\"\n");
        sb.Append("     xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n");
        sb.Append("     version=\"1.1\"\n");
        sb.Append(Invariant($"     width=\"{Num(page.WidthMm)}mm\" height=\"{Num(page.HeightMm)}mm\"\n"));
        sb.Append(Invariant($"     viewBox=\"0 0 {Num(page.WidthMm)} {Num(page.HeightMm)}\">\n"));

        WriteDescription(sb, artwork, page, options);

        if (profile.Flavour == SvgFlavour.Inkscape)
        {
            WriteStyle(sb, profile);
        }

        foreach (var layer in artwork.Layers)
        {
            WriteLayer(sb, layer, page, options);
        }

        sb.Append("</svg>\n");
        return sb.ToString();
    }

    private static void WriteDescription(
        StringBuilder sb, Artwork artwork, SvgPage page, SvgExportOptions options)
    {
        sb.Append("  <title>").Append(Escape(options.Title ?? artwork.Source ?? "PCB_MillBurn")).Append("</title>\n");
        sb.Append("  <desc>\n");
        sb.Append("Generated by PCB_MillBurn.\n");

        if (artwork.Source is not null)
        {
            sb.Append("Source: ").Append(Escape(artwork.Source)).Append('\n');
        }

        sb.Append(Invariant($"Page: {Num(page.WidthMm)} x {Num(page.HeightMm)} mm, "));
        sb.Append(Invariant($"origin at ({Nm.ToMillimetreString(page.Frame.MinX, 4)}, "));
        sb.Append(Invariant($"{Nm.ToMillimetreString(page.Frame.MinY, 4)}) mm in source coordinates.\n"));

        if (options.Mirror)
        {
            sb.Append("Mirrored for bottom-side work.\n");
        }

        // Notes carry the compensations that were applied and anything that could not be
        // realised. Embedding them means the file can answer "why is this 40 um narrow?" months
        // later, without the project that made it.
        foreach (var note in artwork.Notes)
        {
            sb.Append("Note: ").Append(Escape(note)).Append('\n');
        }

        if (options.Timestamp is { } stamp)
        {
            sb.Append("Generated: ").Append(stamp.ToString("u", CultureInfo.InvariantCulture)).Append('\n');
        }

        sb.Append("  </desc>\n");
    }

    private static void WriteStyle(StringBuilder sb, SvgProfile profile)
    {
        sb.Append("  <style>\n");
        foreach (var role in Enum.GetValues<ArtRole>())
        {
            var name = profile.LayerNameFor(role);
            var colour = profile.ColourFor(role);
            sb.Append(Invariant($"    .{name} {{ stroke: {colour}; fill: none; }}\n"));
            sb.Append(Invariant($"    .{name}.filled {{ fill: {colour}; }}\n"));
        }

        sb.Append("  </style>\n");
    }

    private static void WriteLayer(StringBuilder sb, ArtLayer layer, SvgPage page, SvgExportOptions options)
    {
        var profile = options.Profile;
        var colour = profile.ColourFor(layer.Role);
        var className = profile.LayerNameFor(layer.Role);

        sb.Append(Invariant($"  <g id=\"{Escape(layer.Id)}\""));
        sb.Append(Invariant($" inkscape:groupmode=\"layer\" inkscape:label=\"{Escape(layer.Label)}\""));
        sb.Append(Invariant($" class=\"{Escape(className)}\">\n"));

        foreach (var shape in layer.Shapes)
        {
            WriteShape(sb, shape, page, options, colour);
        }

        sb.Append("  </g>\n");
    }

    private static void WriteShape(
        StringBuilder sb, ArtShape shape, SvgPage page, SvgExportOptions options, string colour)
    {
        var d = BuildPathData(shape, page, options.Mirror);
        if (d.Length == 0)
        {
            return;
        }

        sb.Append("    <path d=\"").Append(d).Append('"');

        // Inkscape's flavour inherits colour from the stylesheet, which is the point of having
        // one: the whole drawing re-themes by editing five lines. LightBurn's cannot, because
        // colour there is the layer assignment and must survive an import that may not resolve
        // CSS at all.
        var explicitColour = options.Profile.Flavour == SvgFlavour.LightBurn;

        if (shape.Filled)
        {
            sb.Append(" fill-rule=\"evenodd\"");
            if (explicitColour)
            {
                // Fill is what a human sees; stroke is what LightBurn reads to pick the cut
                // layer. Setting only one of them works in a browser and quietly fails in the
                // tool that matters.
                sb.Append(Invariant($" fill=\"{colour}\" stroke=\"{colour}\" stroke-width=\"0.01\""));
            }
            else
            {
                sb.Append(" class=\"filled\"");
            }
        }
        else
        {
            if (explicitColour)
            {
                sb.Append(Invariant($" fill=\"none\" stroke=\"{colour}\""));
            }

            sb.Append(Invariant($" stroke-width=\"{Num(Nm.ToMillimetres(Math.Max(shape.StrokeWidthNm, 0)))}\""));
            sb.Append(" stroke-linecap=\"round\" stroke-linejoin=\"round\"");
        }

        if (shape.Title is null)
        {
            sb.Append("/>\n");
            return;
        }

        sb.Append(">\n      <title>").Append(Escape(shape.Title)).Append("</title>\n    </path>\n");
    }

    /// <summary>
    /// Builds an SVG <c>d</c> attribute. A new subpath starts wherever a segment does not continue
    /// from the previous one, so a shape whose segments are not contiguous still draws correctly
    /// rather than being joined by a phantom line.
    /// </summary>
    internal static string BuildPathData(ArtShape shape, SvgPage page, bool mirror)
    {
        var sb = new StringBuilder(128);

        foreach (var subpath in shape.Subpaths)
        {
            if (subpath.Count == 0)
            {
                continue;
            }

            Point2? cursor = null;

            foreach (var segment in subpath)
            {
                if (cursor is null || cursor.Value != segment.From)
                {
                    if (sb.Length > 0)
                    {
                        sb.Append(' ');
                    }

                    AppendMove(sb, page.ToPage(segment.From, mirror));
                }

                AppendSegment(sb, segment, page, mirror);
                cursor = segment.To;
            }

            // A closed subpath ends where it began. Saying so with Z matters: an unclosed path
            // fills unpredictably (Documentation/04, section 2.3).
            if (subpath[0].From == subpath[^1].To)
            {
                sb.Append(" Z");
            }
        }

        return sb.ToString();
    }

    private static void AppendMove(StringBuilder sb, Point2 pageNm) =>
        sb.Append('M').Append(' ').Append(Num(Nm.ToMillimetres(pageNm.X)))
          .Append(' ').Append(Num(Nm.ToMillimetres(pageNm.Y)));

    private static void AppendSegment(StringBuilder sb, ArtSegment segment, SvgPage page, bool mirror)
    {
        var to = page.ToPage(segment.To, mirror);

        if (!segment.IsArc)
        {
            sb.Append(" L ").Append(Num(Nm.ToMillimetres(to.X)))
              .Append(' ').Append(Num(Nm.ToMillimetres(to.Y)));
            return;
        }

        var radiusMm = Nm.ToMillimetres((long)Math.Round(segment.RadiusNm, MidpointRounding.AwayFromZero));
        var swept = segment.SweptAngle();

        // SVG's sweep flag counts positive angles, and with Y pointing down that is visually
        // clockwise. Flipping Y therefore turns a Gerber counter-clockwise arc into sweep=1; a
        // mirror flips it back again. Getting this wrong draws the arc the long way round, which
        // on a board outline is unmistakable and on a small fillet is not.
        var sweepFlag = segment.Sweep == ArtSweep.CounterClockwise ? 1 : 0;
        if (mirror)
        {
            sweepFlag = 1 - sweepFlag;
        }

        // SVG cannot express a full circle in one arc: coincident endpoints degenerate to a
        // no-op. Split it at the antipode.
        if (swept >= (2 * Math.PI) - 1e-9)
        {
            var antipode = new Point2(
                (2 * segment.Centre.X) - segment.From.X,
                (2 * segment.Centre.Y) - segment.From.Y);

            AppendArc(sb, page.ToPage(antipode, mirror), radiusMm, largeArc: 0, sweepFlag);
            AppendArc(sb, to, radiusMm, largeArc: 0, sweepFlag);
            return;
        }

        AppendArc(sb, to, radiusMm, swept > Math.PI ? 1 : 0, sweepFlag);
    }

    private static void AppendArc(StringBuilder sb, Point2 pageNm, double radiusMm, int largeArc, int sweep)
    {
        sb.Append(" A ").Append(Num(radiusMm)).Append(' ').Append(Num(radiusMm))
          .Append(" 0 ").Append(largeArc.ToString(CultureInfo.InvariantCulture))
          .Append(' ').Append(sweep.ToString(CultureInfo.InvariantCulture))
          .Append(' ').Append(Num(Nm.ToMillimetres(pageNm.X)))
          .Append(' ').Append(Num(Nm.ToMillimetres(pageNm.Y)));
    }

    /// <summary>
    /// Fixed-precision invariant formatting. The explicit round before formatting keeps
    /// "-0" from ever appearing, which would otherwise be a byte difference between two runs that
    /// mean the same thing.
    /// </summary>
    private static string Num(double value)
    {
        var rounded = Math.Round(value, Decimals, MidpointRounding.AwayFromZero);
        if (rounded == 0)
        {
            rounded = 0;
        }

        return rounded.ToString(NumberFormat, CultureInfo.InvariantCulture);
    }

    private static string Invariant(FormattableString text) => FormattableString.Invariant(text);

    private static string Escape(string text) => text
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal);
}
