using System.Globalization;
using System.Text;
using MillBurn.Core;
using MillBurn.Gcode;

namespace MillBurn.Pipeline;

/// <summary>What the project page needs to know that the files cannot say for themselves.</summary>
public sealed record ProjectPageContext
{
    public required string BoardName { get; init; }

    public required Bounds Board { get; init; }

    public long BoardThicknessNm { get; init; }

    public BlankPlan Blank { get; init; } = BlankPlan.None;

    /// <summary>Anything the export list flagged, so the page carries it too.</summary>
    public IReadOnlyList<string> Skipped { get; init; } = [];
}

/// <summary>
/// One page that says what the whole export is, in the order somebody needs it.
///
/// Requested from the workshop, and the reason is worth keeping: the pieces of this are all said
/// somewhere already — in the export window, in a program's comments, on the drilling page — and
/// each of them is a different place, none of which is open when the folder is opened next week.
///
/// **Short lines.** Every sentence here is read standing up, by somebody deciding what to run next.
/// No paragraphs, no jargon, and no explaining of things the file itself explains — the drilling
/// page says which bit goes in when, and this one says the drilling page exists.
/// </summary>
public static class ProjectPage
{
    /// <summary>Builds the page for a finished plan.</summary>
    public static string Build(ExportPlan plan, ProjectPageContext context)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentNullException.ThrowIfNull(context);

        var page = new StringBuilder(8192);

        page.Append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
        page.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        page.Append("<title>").Append(Escape(context.BoardName)).Append(" — this export</title>\n");
        page.Append("<style>\n").Append(DrillGuide.Style).Append("</style>\n</head>\n<body>\n");

        page.Append("<h1>").Append(Escape(context.BoardName)).Append("</h1>\n");
        page.Append("<p class=\"sub\">Everything in this folder, and what to do with it.</p>\n");

        Facts(page, plan, context);
        Order(page, plan, context);
        Files(page, plan);
        Zero(page, context);
        Laser(page, plan);
        Watch(page, plan, context);

        page.Append("<p class=\"foot\">Generated by PCB_MillBurn. It describes the files beside it; "
            + "if you export again, read it again.</p>\n");
        page.Append("</body>\n</html>\n");

        return page.ToString();
    }

    private static void Facts(StringBuilder page, ExportPlan plan, ProjectPageContext context)
    {
        page.Append("<div class=\"facts\">\n");
        Fact(page, "Board", Size(context.Board));

        if (context.Blank.Resolved)
        {
            Fact(page, "Stock", Size(context.Blank.Bounds));
        }

        if (context.BoardThicknessNm > 0)
        {
            Fact(page, "Thickness", Nm.ToMillimetreString(context.BoardThicknessNm, 2) + " mm");
        }

        Fact(page, "Files", plan.Count.ToString(CultureInfo.InvariantCulture));
        page.Append("</div>\n");
    }

    /// <summary>
    /// The order things happen in, which is the one thing a folder of files cannot show.
    ///
    /// **Suggested, and labelled as such.** Most of it is physical rather than preference — a blank
    /// cut second is not a datum, a slot cut after the board is free moves the board — but not all
    /// of it is, and a board can have a reason to differ that the app cannot see. Somebody meeting
    /// this for the first time should not be able to read a suggestion as an instruction.
    ///
    /// **The laser steps belong here too.** They were missed at first, which made the page read as
    /// though a mixed job were a milling job with some files left over — and a mixed job is the one
    /// where the order is hardest to guess and most expensive to get wrong.
    /// </summary>
    private static void Order(StringBuilder page, ExportPlan plan, ProjectPageContext context)
    {
        bool Any(Func<ExportItem, bool> match) => plan.Items.Any(match);

        var etch = Any(i => i.Output == OutputKind.Svg
            && i.Role is LayerRole.TopCopper or LayerRole.BottomCopper);

        var mask = Any(i => i.Output == OutputKind.Svg
            && i.Role is LayerRole.TopMask or LayerRole.BottomMask);

        var silk = Any(i => i.Output == OutputKind.Svg
            && i.Role is LayerRole.TopSilk or LayerRole.BottomSilk);

        page.Append("<h2>Suggested running order</h2>\n");
        page.Append("<p class=\"sub\">A suggestion, not an instruction. Most of it is physics — the "
            + "blank has to exist before anything is measured from it, and the outline has to be "
            + "last because after it the board is loose — but your board may have a reason to "
            + "differ.</p>\n<ol>\n");

        if (context.Blank is { Resolved: true, Cut: true })
        {
            page.Append("<li><strong>Cut the blank.</strong> Everything else is measured from its "
                + "lower-left corner.</li>\n");
        }
        else if (context.Blank.Resolved)
        {
            page.Append("<li><strong>Put the stock in the corner stop.</strong> Its lower-left "
                + "corner is work zero for every file here.</li>\n");
        }

        // The laser's copper step replaces the mill's, so it comes before everything the mill does
        // to that side rather than alongside it.
        if (etch)
        {
            page.Append("<li><strong>Laser: burn the copper layer.</strong> This is the resist, not "
                + "the copper. <em>Moves to the laser.</em></li>\n");
            page.Append("<li><strong>Etch, then strip the resist.</strong> By hand; nothing here "
                + "does this part.</li>\n");
        }

        if (Any(i => i.Operation == OperationKind.Isolation))
        {
            page.Append("<li><strong>Isolate the copper.</strong>")
                .Append(etch ? " <em>Back to the mill.</em>" : string.Empty)
                .Append("</li>\n");
        }

        if (Any(i => i.Operation == OperationKind.Drilling))
        {
            page.Append("<li><strong>Drill.</strong> The drilling page says which bit, and when it "
                + "stops to change.</li>\n");
        }

        if (Any(i => i.TargetName.Contains(".slots.", StringComparison.Ordinal)))
        {
            page.Append("<li><strong>Route the slots.</strong> End mill, not a drill. The routing "
                + "page says which cutter.</li>\n");
        }

        if (Any(i => i.Operation == OperationKind.Pocket))
        {
            page.Append("<li><strong>Mill the soldermask off the pads.</strong> After the mask is "
                + "on and cured.</li>\n");
        }

        if (mask)
        {
            page.Append("<li><strong>Laser: the soldermask openings.</strong> After the mask is on "
                + "and cured. <em>Moves to the laser.</em></li>\n");
        }

        if (silk)
        {
            page.Append("<li><strong>Laser: the silkscreen.</strong> <em>On the laser.</em></li>\n");
        }

        if (mask || silk)
        {
            page.Append("<li><strong>Back to the mill</strong>, into the same corner stop.</li>\n");
        }

        if (Any(i => i.Operation == OperationKind.Outline
            && !i.TargetName.Contains(".blank.", StringComparison.Ordinal)))
        {
            page.Append("<li><strong>Cut the board out.</strong> Last: after this it is loose, so "
                + "anything needing it held has to have happened already.</li>\n");
        }

        page.Append("</ol>\n");

        if (etch || mask || silk)
        {
            page.Append("<div class=\"note\"><p>The work moves between machines here. Each time it "
                + "goes back, it goes into the same corner stop the same way round — that is what "
                + "keeps the two machines agreeing.</p></div>\n");
        }
    }

    private static void Files(StringBuilder page, ExportPlan plan)
    {
        page.Append("<h2>The files</h2>\n<table>\n<thead><tr><th>File</th><th>What it is</th>"
            + "<th>Machine</th></tr></thead>\n<tbody>\n");

        foreach (var item in plan.Items)
        {
            page.Append("<tr><td><code>").Append(Escape(item.TargetName)).Append("</code></td>")
                .Append("<td>").Append(Escape(What(item))).Append("</td>")
                .Append("<td>").Append(item.Output == OutputKind.Svg ? "Laser" : "Mill").Append("</td></tr>\n");

            if (item.Companion is { } companion)
            {
                page.Append("<tr><td><code>").Append(Escape(companion.TargetName)).Append("</code></td>")
                    .Append("<td>Read this before running the file above.</td>")
                    .Append("<td>—</td></tr>\n");
            }
        }

        page.Append("</tbody>\n</table>\n");
    }

    private static void Zero(StringBuilder page, ProjectPageContext context)
    {
        page.Append("<h2>Work zero</h2>\n<ul>\n");

        page.Append(context.Blank.Resolved
            ? "<li>The <strong>lower-left corner of the stock</strong>, not of the board.</li>\n"
            : "<li>The <strong>lower-left corner of the board</strong>.</li>\n");

        if (context.Blank.Resolved)
        {
            page.Append("<li>The board sits <strong>")
                .Append(Nm.ToMillimetreString(context.Board.MinX - context.Blank.Bounds.MinX, 2))
                .Append(" mm right</strong> and <strong>")
                .Append(Nm.ToMillimetreString(context.Board.MinY - context.Blank.Bounds.MinY, 2))
                .Append(" mm up</strong> from it.</li>\n");
        }

        page.Append("<li>Every file here uses the same zero.</li>\n");
        page.Append("<li><strong>Set Z again after every tool change</strong>, on the same spot each "
            + "time.</li>\n");
        page.Append("</ul>\n");
    }

    /// <summary>
    /// The one that caused this page to be asked for.
    ///
    /// The SVGs share a page, and the page is bigger than the artwork — so software that imports by
    /// the drawing's own bounds drops the border and lands everything at the origin, out by exactly
    /// that border. The number is stated rather than left to be worked out.
    /// </summary>
    private static void Laser(StringBuilder page, ExportPlan plan)
    {
        var svgs = plan.Items.Where(i => i.Output == OutputKind.Svg).ToList();

        if (svgs.Count == 0)
        {
            return;
        }

        page.Append("<h2>Placing the SVGs</h2>\n<ul>\n");
        page.Append("<li>They all share one page, so they line up with each other.</li>\n");
        page.Append("<li>Put the <strong>page's</strong> lower-left corner on work zero.</li>\n");

        foreach (var line in svgs[0].Summary.Where(s => s.Contains("artwork sits", StringComparison.Ordinal)))
        {
            page.Append("<li>").Append(Escape(line)).Append("</li>\n");
        }

        page.Append("</ul>\n");

        page.Append("<div class=\"warn\"><p><strong>Do not centre them.</strong> Some laser software "
            + "imports the drawing rather than the page: it throws the empty border away and puts "
            + "the artwork at the origin. That is out by the border, and it looks right. Place by "
            + "the page, or add the offset above by hand.</p></div>\n");
    }

    private static void Watch(StringBuilder page, ExportPlan plan, ProjectPageContext context)
    {
        var warnings = plan.Items
            .SelectMany(i => i.Warnings)
            .Concat(context.Skipped)
            .Distinct(StringComparer.Ordinal)
            .ToList();

        if (warnings.Count == 0)
        {
            return;
        }

        page.Append("<h2>Worth checking</h2>\n<ul>\n");

        foreach (var warning in warnings)
        {
            page.Append("<li>").Append(Escape(warning)).Append("</li>\n");
        }

        page.Append("</ul>\n");
    }

    private static string What(ExportItem item) => item.TargetName switch
    {
        var n when n.Contains(".blank.", StringComparison.Ordinal) => "Cuts the stock to size",
        var n when n.Contains(".slots.", StringComparison.Ordinal) => "Slots and milled holes",
        var n when n.Contains(".dryrun.", StringComparison.Ordinal) => "The same path, in the air",
        var n when n.Contains(".levelled.", StringComparison.Ordinal) => "Bent to the probed surface",
        _ => item.LayerLabel + " · " + LayerOperations.Label(item.Operation),
    };

    private static string Size(Bounds b) =>
        Nm.ToMillimetreString(b.Width, 2) + " × " + Nm.ToMillimetreString(b.Height, 2) + " mm";

    private static void Fact(StringBuilder page, string label, string value) =>
        page.Append("<div><span>").Append(Escape(label)).Append("</span><strong>")
            .Append(Escape(value)).Append("</strong></div>\n");

    private static string Escape(string text) => text
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal);
}
