namespace MillBurn.Gcode;

/// <summary>
/// The last line of every page this app writes beside a program.
///
/// One line, and it has to survive being read in a workshop. The pages are self-contained by rule —
/// no network, no stylesheet beside them, nothing installed — so a link to the help can only ever
/// be a *local* one, and a local link is only good on the machine that made it. A folder copied to
/// a laptop, or e-mailed to somebody, takes its pages with it and leaves the app behind.
///
/// So: link where the help can actually be found, and **always name the menu** as well. The link is
/// a convenience; the sentence is the answer. A footer that offers only a link is a footer that
/// says nothing at all the first time it is read somewhere else.
/// </summary>
public static class GuideFooter
{
    /// <summary>
    /// Where the shipped help lives, or null when it cannot be found.
    ///
    /// Walked up from wherever the assembly is rather than assumed, because the app runs from
    /// `out/windows` when published and from `bin/Release/net10.0` when it is not, and the help
    /// sits beside the executable in one and several levels up in the other.
    /// </summary>
    public static string? HelpPath { get; } = Find();

    /// <summary>
    /// The footer, with a link into the help at <paramref name="anchor"/> when there is one.
    /// </summary>
    /// <param name="about">What this page describes, for the first sentence.</param>
    /// <param name="anchor">FAQ section id — "drilling", "drills", "project-page".</param>
    public static string For(string about, string anchor)
    {
        ArgumentNullException.ThrowIfNull(about);
        ArgumentNullException.ThrowIfNull(anchor);

        var more = HelpPath is { } path
            ? $"<a href=\"{Escape(Uri(path))}#{Escape(anchor)}\">More in the help</a>, or "
            : "More in the help: ";

        return "<p class=\"foot\">Generated by PCB_MillBurn. " + about
            + "<br>" + more
            + "<strong>Help &rsaquo; Questions and answers</strong> in the app, or press F1.</p>\n";
    }

    private static string Uri(string path) =>
        "file:///" + path.Replace('\\', '/').TrimStart('/');

    private static string? Find()
    {
        var at = new DirectoryInfo(AppContext.BaseDirectory);

        while (at is not null)
        {
            var faq = Path.Combine(at.FullName, "Help", "faq.html");

            if (File.Exists(faq))
            {
                return faq;
            }

            at = at.Parent;
        }

        return null;
    }

    private static string Escape(string text) => text
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal);
}
