using System.Globalization;
using System.Text;
using MillBurn.Core;
using static System.FormattableString;

namespace MillBurn.Gcode;

/// <summary>
/// The page written beside a test cut, explaining how to read it.
///
/// A coupon with six lines on it is not a result. What makes it one is knowing which line is which,
/// what each was supposed to measure, and what to do with the difference — and none of that is
/// visible in a piece of copper or in the G-code that made it. The program is the experiment; this
/// is the method and the analysis.
/// </summary>
public static class TestCutGuide
{
    /// <summary>Builds the page for a test that has just been planned.</summary>
    public static string Build(
        TestCutOptions options, TestCutReport report, string programName, string? levelledTo = null)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(report);

        var tool = options.Tool;
        var page = new StringBuilder();

        page.Append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
        page.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        page.Append("<title>").Append(Escape(Title(options.Kind))).Append("</title>\n");
        page.Append("<style>\n").Append(Style).Append("</style>\n</head>\n<body>\n");

        page.Append("<h1>").Append(Escape(Title(options.Kind))).Append("</h1>\n");
        page.Append("<p class=\"sub\">").Append(Escape(tool.Name))
            .Append(" &middot; <code>").Append(Escape(programName)).Append("</code></p>\n");

        Facts(page, options, report);
        Before(page, options, report);
        Table(page, options, report);
        LadderSection(page, report);
        Analysis(page, options, report);
        Trouble(page, options, report);
        Flatness(page, options, report, levelledTo);

        page.Append("<p class=\"foot\">Generated by PCB_MillBurn. This page describes the program beside it; ")
            .Append("if you change the numbers and export again, read it again.</p>\n");

        page.Append("</body>\n</html>\n");

        return page.ToString();
    }

    private static string Title(TestCutKind kind) => kind == TestCutKind.Depth
        ? "Depth and width test"
        : "Feed rate test";

    // ------------------------------------------------------------------ the numbers at the top

    private static void Facts(StringBuilder page, TestCutOptions options, TestCutReport report)
    {
        page.Append("<div class=\"facts\">\n");

        Fact(page, "Lines", report.Lines.Count.ToString(CultureInfo.InvariantCulture));
        Fact(page, "Stock", Invariant($"{report.StockWidthMm:F0} &times; {report.StockHeightMm:F0} mm"));
        Fact(page, "Time", Invariant($"{Math.Max(1, Math.Round(report.EstimatedSeconds / 5) * 5):F0} sec"));

        Fact(
            page,
            options.Kind == TestCutKind.Depth ? "Depths" : "Feeds",
            options.Kind == TestCutKind.Depth
                ? Invariant($"{report.Lines.Min(l => l.DepthMm):F3}&ndash;{report.Lines.Max(l => l.DepthMm):F3} mm")
                : Invariant($"{report.Lines.Min(l => l.FeedMmPerMin):F0}&ndash;{report.Lines.Max(l => l.FeedMmPerMin):F0} mm/min"));

        page.Append("</div>\n");
    }

    private static void Fact(StringBuilder page, string label, string value) =>
        page.Append("<div><span>").Append(label).Append("</span><strong>")
            .Append(value).Append("</strong></div>\n");

    // ------------------------------------------------------------------ setting it up

    private static void Before(StringBuilder page, TestCutOptions options, TestCutReport report)
    {
        page.Append("<h2>Before you run it</h2>\n<ul>\n");

        page.Append("<li>Use <strong>scrap copper-clad</strong>, not a board you want. It needs ")
            .Append(Invariant($"{report.StockWidthMm:F0} &times; {report.StockHeightMm:F0} mm"))
            .Append(" of bare copper.</li>\n");

        page.Append("<li><strong>Hold it down across its whole area</strong> &mdash; double-sided tape ")
            .Append("under all of it, or a vacuum bed. Not tape at the corners. A probe triggers at ")
            .Append("no force and a cutter does not, so an unsupported middle moves away from the ")
            .Append("tool and every width on the coupon is wrong by an amount that varies along it.</li>\n");

        page.Append("<li><strong>Work zero is the lower-left corner of the scrap, on the copper.</strong> ")
            .Append("Touch Z off on the copper itself, not on the table and not on the vice.</li>\n");

        page.Append("<li>Line 1 is nearest that corner. Every line runs left to right, and they are ")
            .Append(Invariant($"{options.LineSpacingMm:F1} mm apart.</li>\n"));

        if (options.Kind == TestCutKind.Feed)
        {
            page.Append("<li>Every line is the same depth. The only thing that changes is how fast ")
                .Append("the tool crosses.</li>\n");
        }

        page.Append("</ul>\n");

        foreach (var warning in report.Warnings)
        {
            page.Append("<p class=\"warn\">").Append(Escape(warning)).Append("</p>\n");
        }

        foreach (var note in report.Notes)
        {
            page.Append("<p class=\"note\">").Append(Escape(note)).Append("</p>\n");
        }
    }

    // ------------------------------------------------------------------ the lines

    private static void Table(StringBuilder page, TestCutOptions options, TestCutReport report)
    {
        var banded = options.Kind == TestCutKind.Depth && report.Lines[0].PassCount > 1;

        page.Append("<h2>What each line is</h2>\n<table>\n<tr><th>#</th><th>Depth</th>");

        page.Append(options.Kind != TestCutKind.Depth
            ? "<th>Feed</th><th>Per tooth</th>"
            : banded
                ? "<th>One pass</th><th>Predicted band</th><th>MEASURED band</th>"
                : "<th>Predicted width</th><th>Measured</th>");

        page.Append("<th>Y</th></tr>\n");

        foreach (var line in report.Lines.Where(l => !l.IsLadder))
        {
            page.Append("<tr><td>").Append(line.Number);

            if (line.IsRepeat)
            {
                page.Append(" <span class=\"tag\">repeat of 1</span>");
            }

            page.Append("</td><td>").Append(Invariant($"{line.DepthMm:F3} mm</td>"));

            page.Append(options.Kind != TestCutKind.Depth
                ? Invariant($"<td>{line.FeedMmPerMin:F0} mm/min</td><td>{line.ChipLoadNm / 1000:F1} &micro;m</td>")
                : banded
                    ? Invariant($"<td>{line.PredictedWidthMm:F3} mm</td><td>{line.BandWidthMm:F3} mm</td><td class=\"blank\">&nbsp;</td>")
                    : Invariant($"<td>{line.PredictedWidthMm:F3} mm</td><td class=\"blank\">&nbsp;</td>"));

            page.Append(Invariant($"<td>{line.YMm:F1} mm</td></tr>\n"));
        }

        page.Append("</table>\n");

        if (options.Kind != TestCutKind.Depth)
        {
            return;
        }

        page.Append("<p class=\"note\">Print this page and write the measurements in the blank ")
            .Append("column. The predicted figures are what the tool library currently believes; ")
            .Append("the point of the test is to find out whether it is right.</p>\n");

        if (!banded)
        {
            return;
        }

        var stepped = report.Lines[0].SteppedMm;

        // The deepest line, not the last one. The last one is the repeat of line 1, which is the
        // shallowest — quoting it here read "0.150 mm at the shallowest and 0.150 at the deepest".
        var deepest = report.Lines.Where(l => !l.IsLadder).MaxBy(l => l.DepthMm);

        // The arithmetic, spelled out, because it is the whole reason the bands are wide.
        page.Append("<h3>Why the band, and what to do with it</h3>\n")
            .Append("<p>One pass of this bit is ")
            .Append(Invariant($"{report.Lines[0].PredictedWidthMm:F3}&nbsp;mm at the shallowest line "))
            .Append(Invariant($"and {deepest.PredictedWidthMm:F3}&nbsp;mm at the deepest. "))
            .Append("Those are not widths a caliper can measure — you cannot get a jaw onto them at ")
            .Append("all, and reading a few hundredths off a groove that narrow is guesswork. ")
            .Append(Invariant($"So each line is cut {report.Lines[0].PassCount} times, stepping "))
            .Append(Invariant($"{report.Lines[0].StepoverMm:F3}&nbsp;mm each time, which puts the same "))
            .Append("information on a band about two millimetres across.</p>\n")
            .Append("<p><strong>Measure the band, then subtract ")
            .Append(Invariant($"{stepped:F3}&nbsp;mm.</strong> "))
            .Append("That number is the ground the passes stepped over. It is commanded rather ")
            .Append("than observed, so it is exact, and it is <em>the same on every line</em> — ")
            .Append("which is what makes this work. Your caliper's error is mostly a fixed bias, ")
            .Append("and a fixed bias cancels when you compare one line against another.</p>\n")
            .Append("<p>You can skip the subtraction entirely if you only want the angle: the ")
            .Append("band grows with depth at exactly the rate the cut does, so the slope of ")
            .Append("measured band against depth is the same slope, offset and all.</p>\n");

        page.Append("<div class=\"warn\"><p><strong>If you can see ribs of copper left between ")
            .Append("the passes of these bands, the bit is cutting far narrower than the library ")
            .Append(Invariant($"claims</strong> &mdash; under {report.Lines[0].StepoverMm:F3}&nbsp;mm "))
            .Append(Invariant($"at {report.Lines[0].DepthMm:F3}&nbsp;mm deep, against the "))
            .Append(Invariant($"{report.Lines[0].PredictedWidthMm:F3}&nbsp;mm it expects. The ladder "))
            .Append("below is built to find exactly that, and to say by how much.</p></div>\n");
    }

    // ------------------------------------------------------------------ the width ladder

    /// <summary>
    /// The rungs, what each should look like, and what the one that changes tells you.
    ///
    /// This exists because a single measurement cannot be checked. A band that comes out close to
    /// its prediction is either a bit that matches its library or a reading taken slightly wrong,
    /// and nothing on the coupon separates those. The ladder answers a different shape of question
    /// — not "is this number right" but "where does this row of samples change" — and that is the
    /// kind of question an eye is good at and an instrument is not needed for.
    /// </summary>
    private static void LadderSection(StringBuilder page, TestCutReport report)
    {
        var rungs = report.Lines.Where(l => l.IsLadder).ToList();

        if (rungs.Count < 2)
        {
            return;
        }

        var believed = rungs[0].PredictedWidthMm;
        // The rung nearest the believed width, rather than the first at or above it. Stepovers are
        // rounded to four places when the ladder is planned, so the rung meant to sit exactly on
        // the believed width lands a few ten-thousandths under it and any "at or above" test puts
        // the label one rung too high.
        var matching = rungs
            .Select((r, i) => (Index: i, Off: Math.Abs(r.StepoverMm - believed)))
            .MinBy(x => x.Off)
            .Index;

        page.Append("<h2>The width ladder</h2>\n");

        page.Append("<p>The lines above measure how the cut <em>changes</em> with depth. These ")
            .Append(Invariant($"{rungs.Count} rungs measure what it actually <em>is</em>, at "))
            .Append(Invariant($"{rungs[0].DepthMm:F3}&nbsp;mm deep, and they do it without a caliper.</p>\n"));

        page.Append("<p>Every rung is the same depth and the same ")
            .Append(Invariant($"{rungs[0].PassCount} passes. What climbs is the stepover, from "))
            .Append(Invariant($"{rungs[0].StepoverMm:F3} to {rungs[^1].StepoverMm:F3}&nbsp;mm. "))
            .Append("Step over by less than the bit cuts and the passes overlap, so the rung comes ")
            .Append("out as one clean band. Step over by more and they leave <strong>hairlines of ")
            .Append("copper standing between them</strong>. So:</p>\n");

        page.Append("<p class=\"big\">The first rung with copper left in it is how wide this bit ")
            .Append("really cuts.</p>\n");

        page.Append("<table>\n<tr><th>Rung</th><th>Stepover</th><th>If the library is right</th>")
            .Append("<th>SOLID or RIBBED</th></tr>\n");

        for (var i = 0; i < rungs.Count; i++)
        {
            var rung = rungs[i];

            page.Append("<tr><td>").Append(rung.Number);

            if (i == matching)
            {
                page.Append(" <span class=\"tag\">the library's answer</span>");
            }

            page.Append(Invariant($"</td><td>{rung.StepoverMm:F3} mm</td><td>"));

            page.Append(rung.PredictedRibMm > 0.0005
                ? Invariant($"ribbed, {rung.PredictedRibMm:F3} mm of copper")
                : rung.PredictedRibMm < -0.0005
                    ? Invariant($"solid, overlapping {-rung.PredictedRibMm:F3} mm")
                    : "exactly touching");

            page.Append("</td><td class=\"blank\">&nbsp;</td></tr>\n");
        }

        page.Append("</table>\n");

        page.Append("<p>Drawn to scale, the bottom rung and the top rung should look like this:</p>\n");
        page.Append("<div class=\"rungs\">\n");
        Diagram(page, rungs[0], "Rung " + rungs[0].Number.ToString(CultureInfo.InvariantCulture) + " — solid");
        Diagram(page, rungs[^1], "Rung " + rungs[^1].Number.ToString(CultureInfo.InvariantCulture) + " — ribbed");
        page.Append("</div>\n");

        page.Append("<h3>Which way to move the number</h3>\n<ul>\n");

        page.Append("<li><strong>Copper appears at a rung ")
            .Append(Invariant($"below {rungs[matching].Number}</strong> &mdash; "))
            .Append("the bit cuts <em>narrower</em> than the library says. Your isolation is ")
            .Append("clearing a thinner moat than the app believes, so the gaps between nets are ")
            .Append("smaller than you asked for. Reduce the tip width.</li>\n");

        page.Append("<li><strong>Every rung is solid, including the top one</strong> &mdash; the bit ")
            .Append("cuts <em>wider</em> than the library says, by at least ")
            .Append(Invariant($"{rungs[^1].StepoverMm - believed:F3}&nbsp;mm. "))
            .Append("Increase the tip width. Run the ladder again with a higher stepover to pin it.</li>\n");

        page.Append("<li><strong>The change falls where the table says it should</strong> &mdash; ")
            .Append("the library describes your bit at this depth, and you now know that rather ")
            .Append("than hoping it.</li>\n");

        page.Append("</ul>\n");

        page.Append("<p class=\"note\">The ladder fixes the width at one depth; the lines above fix ")
            .Append("how it grows with depth. You need both, because a tip that is too small and an ")
            .Append("angle that is too shallow look identical on a single line.</p>\n");

        page.Append("<div class=\"warn\"><p><strong>A rib can tear off instead of standing.</strong> ")
            .Append("The thinnest ones sometimes lift with the chip rather than survive, which makes ")
            .Append("a rung look solid when it was not quite. That bias runs one way only, so read ")
            .Append("the first <em>clearly</em> ribbed rung as an upper bound and the last clearly ")
            .Append("solid one as a lower bound.</p></div>\n");
    }

    /// <summary>
    /// A rung drawn at true proportions: the copper, and the cut each pass takes out of it.
    ///
    /// Drawn rather than photographed. A photograph of somebody else's coupon under somebody else's
    /// light is a poor standard to judge your own against, and this only has to answer "how much
    /// copper, and how far apart".
    /// </summary>
    private static void Diagram(StringBuilder page, TestCutLine rung, string caption)
    {
        const double Width = 300;
        const double Height = 54;

        var span = rung.BandWidthMm;
        var scale = span > 0 ? Width / span : 1;
        var cut = rung.PredictedWidthMm * scale;

        page.Append("<figure>\n<svg viewBox=\"0 0 ")
            .Append(Invariant($"{Width + 2:F0} {Height:F0}\" width=\"100%\" role=\"img\">\n"))
            .Append(Invariant($"<rect x=\"1\" y=\"1\" width=\"{Width:F1}\" height=\"{Height - 2:F1}\" fill=\"#c0763a\"/>\n"));

        for (var pass = 0; pass < rung.PassCount; pass++)
        {
            var x = 1 + (pass * rung.StepoverMm * scale);

            page.Append(Invariant(
                $"<rect x=\"{x:F2}\" y=\"1\" width=\"{cut:F2}\" height=\"{Height - 2:F1}\" fill=\"#26302b\"/>\n"));
        }

        page.Append("</svg>\n<figcaption>").Append(Escape(caption))
            .Append(Invariant($" &middot; stepping {rung.StepoverMm:F3} mm</figcaption>\n</figure>\n"));
    }

    // ------------------------------------------------------------------ reading it

    private static void Analysis(StringBuilder page, TestCutOptions options, TestCutReport report)
    {
        page.Append("<h2>Reading the result</h2>\n");

        if (options.Kind == TestCutKind.Depth)
        {
            DepthAnalysis(page, options, report);
        }
        else
        {
            FeedAnalysis(page, options);
        }
    }

    private static void DepthAnalysis(StringBuilder page, TestCutOptions options, TestCutReport report)
    {
        page.Append("<p><strong>Measure across the middle of each line</strong>, not at the ends. ")
            .Append("The tool plunges at one end and leaves at the other, and both ends lie. A loupe ")
            .Append("with a scale, a microscope, or calipers on a good light will all do it; you are ")
            .Append("looking for a few hundredths, so read the same way every time.</p>\n");

        page.Append("<h2>What the answer means</h2>\n<ul>\n");

        page.Append("<li><strong>Measurements match the predictions.</strong> The tool library ")
            .Append("describes your bit. Nothing to do &mdash; and now you know, rather than ")
            .Append("assume.</li>\n");

        page.Append("<li><strong>Every line is wider than predicted by about the same amount.</strong> ")
            .Append("That is the <em>tip</em>, and it is the common case. The tip width in the library ")
            .Append("is too small; the difference between measured and predicted is roughly how much ")
            .Append("to add. Listings quote tip width in inches surprisingly often &mdash; 0.005&nbsp;in ")
            .Append("is 0.127&nbsp;mm &mdash; so check the units before reaching for the calculator.</li>\n");

        page.Append("<li><strong>The error grows with depth.</strong> That is the <em>angle</em>. A ")
            .Append("bit ground steeper than its label widens faster than the model expects. Work the ")
            .Append("angle out from any two lines: ")
            .Append("<code>tan(angle / 2) = (w&#8322; &minus; w&#8321;) / (2 &times; (d&#8322; &minus; d&#8321;))</code>.</li>\n");

        page.Append("<li><strong>Nothing cut at all on the first line or two.</strong> Z zero is ")
            .Append("high, or the surface is not flat. Re-zero and run it again before believing any ")
            .Append("of it.</li>\n");

        page.Append("<li><strong>The widths wander up and down rather than climbing steadily.</strong> ")
            .Append("The stock is not flat or not held. Fix that first; this test cannot tell you ")
            .Append("anything until it is.</li>\n");

        page.Append("</ul>\n");

        page.Append("<p>You can also work the tip out directly from a single line: ")
            .Append("<code>tip = width &minus; 2 &times; depth &times; tan(angle / 2)</code>. For ")
            .Append(Invariant($"this bit at {report.Lines[0].DepthMm:F3} mm, a width of "))
            .Append(Invariant($"{report.Lines[0].PredictedWidthMm:F3} mm would mean the library is exactly right"));

        page.Append(report.Lines[0].PassCount > 1
            ? Invariant($" &mdash; which is a band of {report.Lines[0].BandWidthMm:F3} mm, the width being what is left once {report.Lines[0].SteppedMm:F3} mm is taken off.</p>\n")
            : ".</p>\n");

        page.Append("<p><strong>Put the answer back in the tool library</strong> ")
            .Append("&mdash; <em>Edit &rarr; Tool library</em>. Every isolation job on this machine ")
            .Append("is computed from that number, including how many passes a given isolation width ")
            .Append("takes, so correcting it fixes more than this one measurement.</p>\n");
    }

    private static void FeedAnalysis(StringBuilder page, TestCutOptions options)
    {
        page.Append("<p><strong>Look at the edges, not the widths.</strong> Every line here is the ")
            .Append("same depth, so they should all be the same width; what changes is how clean the ")
            .Append("copper edge is. Use a loupe, and look along the line rather than at one spot.</p>\n");

        page.Append("<h2>What you are looking for</h2>\n<ul>\n");

        page.Append("<li><strong>Too slow</strong> &mdash; the edge is rough and torn, the copper is ")
            .Append("smeared rather than cut, and there may be a burr you can feel. The tool is ")
            .Append("rubbing instead of taking a chip, which blunts it fast and work-hardens the ")
            .Append("copper in front of the cut. Slower is not gentler.</li>\n");

        page.Append("<li><strong>Right</strong> &mdash; a crisp edge, a consistent width along the ")
            .Append("whole line, and a fine dry dust rather than fluff.</li>\n");

        page.Append("<li><strong>Too fast</strong> &mdash; the line wanders, the width varies, the ")
            .Append("edge is chipped, or the machine sounds like it is being asked for too much. On a ")
            .Append("fine bit the next thing that happens is that it breaks.</li>\n");

        page.Append("</ul>\n");

        page.Append("<p>The <em>per tooth</em> column is the real quantity: how far the tool advances ")
            .Append("per flute per revolution. Below about ")
            .Append(Invariant($"{ToolAdvice.RubbingBelowNm / 1000:F0}&nbsp;&micro;m"))
            .Append(" it is rubbing rather than cutting whatever the feed says, and that figure does ")
            .Append("not change when you change bits &mdash; so once you know the number that works, ")
            .Append("it carries over.</p>\n");

        page.Append("<p><strong>Pick the fastest line that still looks clean</strong>, not the ")
            .Append("cleanest one. Cutting slower than necessary costs hours on a dense board and ")
            .Append("wears the bit faster, and the cleanest line is usually one step slower than it ")
            .Append("needs to be. Put that feed into the tool library &mdash; ")
            .Append("<em>Edit &rarr; Tool library</em>.</p>\n");

        page.Append("<p class=\"note\">Spindle speed is the same on every line here, taken from the ")
            .Append("tool. If nothing in the range looks right, change the spindle speed and run the ")
            .Append("test again: feed and speed are one setting with two dials.</p>\n");
    }

    // ------------------------------------------------------------------ when it goes wrong

    private static void Trouble(StringBuilder page, TestCutOptions options, TestCutReport report)
    {
        if (!options.RepeatFirstLine || report.Lines.Count < 2)
        {
            return;
        }

        page.Append("<h2>Check this first</h2>\n");

        page.Append("<p><strong>Line ").Append(report.Lines[^1].Number)
            .Append(" is a repeat of line 1</strong>, cut last and at the far end of the coupon. ")
            .Append("Measure both. If they do not match, something moved between one end of the ")
            .Append("stock and the other &mdash; it is tilted, it is not held down, or Z drifted ")
            .Append("during the run &mdash; and every other number on the coupon is off by an ")
            .Append("unknown, varying amount.</p>\n");

        page.Append("<p>That check costs one line and about four seconds, and it is the difference ")
            .Append("between a measurement and a guess.</p>\n");
    }

    // ------------------------------------------------------------------ if the scrap is bowed

    /// <summary>
    /// What to do when the coupon is not flat enough for the numbers to mean anything.
    ///
    /// The important half is the refusal: **not** the board's height map. A map describes one piece
    /// of stock as it was clamped, and a test coupon is a different piece in a different place. It
    /// would be applied confidently and be wrong everywhere, which is the failure this whole app is
    /// arranged against.
    /// </summary>
    private static void Flatness(
        StringBuilder page, TestCutOptions options, TestCutReport report, string? levelledTo)
    {
        page.Append("<h2>If the scrap is not flat</h2>\n");

        if (levelledTo is not null)
        {
            page.Append("<p><strong>This program is already levelled</strong> to ")
                .Append(Escape(levelledTo))
                .Append(". Every Z in it follows that surface, so work zero has to be in exactly ")
                .Append("the same place as it was when you probed &mdash; do not re-zero in ")
                .Append("between. The rest of this section is why that was worth doing.</p>\n");
        }

        page.Append("<p>Depth error and width error are the same thing here. A coupon ")
            .Append(Invariant($"{report.StockHeightMm:F0} mm across that is a couple of hundredths out of flat "))
            .Append("shifts every line by about as much as ");

        page.Append(options.Kind == TestCutKind.Depth
            ? Invariant($"the {options.DepthStepMm:F3} mm step between them")
            : "the depth you are testing at");

        page.Append(", which turns the result into noise that looks like data.</p>\n");

        page.Append("<p><strong>Hold it down properly first.</strong> That fixes most of it and ")
            .Append("costs nothing. The repeat line at the end tells you whether it worked: if it ")
            .Append("matches line 1, the coupon was flat enough and you can stop worrying about ")
            .Append("this.</p>\n");

        page.Append("<p>If it still is not flat enough &mdash; thin stock, or a machine bed that is ")
            .Append("not &mdash; probe <em>this coupon</em> and level the test file against that:</p>\n");

        page.Append("<ul>\n")
            .Append("<li>Write a probing routine for the coupon &mdash; the same dialog offers one, ")
            .Append("sized to the area this test uses.</li>\n")
            .Append("<li>Run it, keep your sender's log, and import it.</li>\n")
            .Append("<li>Level this file against that log.</li>\n")
            .Append("</ul>\n");

        page.Append("<p class=\"warn\"><strong>Do not level a test cut with the board's height ")
            .Append("map.</strong> A map describes one piece of stock in the position it was ")
            .Append("clamped in, and this coupon is a different piece in a different place. Applied ")
            .Append("to it the correction would be confident and wrong everywhere &mdash; and the ")
            .Append("file would look exactly as trustworthy as one that was right.</p>\n");
    }

    // ------------------------------------------------------------------ plumbing

    private static string Escape(string text) => text
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal);

    private const string Style = """
        :root { color-scheme: light dark; --rule: #d9dce1; --muted: #5b6470; --warn: #b3261e; --tint: #eef1f5; }
        @media (prefers-color-scheme: dark) {
          :root { --rule: #333941; --muted: #9aa4b2; --warn: #ff6b63; --tint: #1c2127; }
        }
        body {
          font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
          max-width: 46rem; margin: 2rem auto; padding: 0 1.25rem;
        }
        h1 { font-size: 1.5rem; margin: 0 0 0.15rem; }
        h2 { font-size: 1.05rem; margin: 2rem 0 0.5rem; }
        .sub { color: var(--muted); margin: 0 0 1.5rem; }
        code { font-family: ui-monospace, Consolas, monospace; background: var(--tint); padding: 0.05rem 0.3rem; border-radius: 3px; }
        .facts { display: flex; flex-wrap: wrap; gap: 1.75rem; padding: 0.9rem 0; border-block: 1px solid var(--rule); }
        .facts div { display: flex; flex-direction: column; }
        .facts span { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }
        .facts strong { font-size: 1.2rem; }
        table { border-collapse: collapse; width: 100%; }
        th, td { text-align: left; padding: 0.5rem 0.75rem 0.5rem 0; border-bottom: 1px solid var(--rule); }
        th { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); font-weight: 600; }
        .blank { border-bottom: 1px solid var(--muted); min-width: 6rem; }
        .tag { font-size: 0.7rem; color: var(--muted); }
        ul { padding-left: 1.1rem; }
        li { margin: 0.5rem 0; }
        .warn { border-left: 3px solid var(--warn); padding: 0.1rem 0 0.1rem 0.9rem; margin: 1rem 0; }
        .note { color: var(--muted); }
        .big { font-size: 1.1rem; font-weight: 600; margin: 1.2rem 0; }
        .rungs { display: flex; flex-wrap: wrap; gap: 1.5rem; margin: 1rem 0 1.5rem; }
        .rungs figure { margin: 0; flex: 1 1 16rem; }
        .rungs svg { display: block; border: 1px solid var(--rule); }
        figcaption { font-size: 0.78rem; color: var(--muted); margin-top: 0.35rem; }
        .foot { color: var(--muted); font-size: 0.8rem; margin-top: 2.5rem; }
        """;
}
