<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MillBurn.Core\MillBurn.Core.csproj" />
    <ProjectReference Include="..\MillBurn.Geometry\MillBurn.Geometry.csproj" />
    <ProjectReference Include="..\MillBurn.Gerber\MillBurn.Gerber.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
